### ISSUE TITLE
Grib2 SubMessageIterator returns only first SubMessage

### ISSUE THREAD

**Issue by Quba1** [noritada/grib-rs#13]
### Simple Description on the Bug

A `for` loop:

```rust
let grib2 = Grib2::<SeekableGrib2Reader<BufReader<File>>>::read_with_seekable(f)?;

for submessage in grib2.iter() {}
```

returns only the first message from the `.grib` file, instead of all messages that this file contains, even though all messages can be read with the crate.

### Steps to Reproduce

The folder contains files from the ERA5 dataset (converted with ecCodes library), where `_p#` files are a submessages from the `era5.grib` copied into separate files:

```bash
user@user-Computer:~/grib-test$ ls -l
total 26388
-rw-rw-r-- 1 user user 13498296 lis  9 17:01 era5.grib
-rw-rw-r-- 1 user user  2076676 lis  9 17:09 era5_p1.grib
-rw-rw-r-- 1 user user  2076676 lis  9 17:09 era5_p2.grib
-rw-rw-r-- 1 user user  2076676 lis  9 17:09 era5_p3.grib
-rw-rw-r-- 1 user user  2076676 lis  9 17:09 era5_p4.grib
-rw-rw-r-- 1 user user  3114916 lis  9 17:10 era5_p5.grib
-rw-rw-r-- 1 user user  2076676 lis  9 17:10 era5_p6.grib
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5.grib
era5.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            10u          regular_ll   grid_simple  10           heightAboveGround 
2            10v          regular_ll   grid_simple  10           heightAboveGround 
2            2d           regular_ll   grid_simple  2            heightAboveGround 
2            2t           regular_ll   grid_simple  2            heightAboveGround 
2            z            regular_ll   grid_simple  0            surface     
2            sp           regular_ll   grid_simple  0            surface     
6 of 6 messages in era5.grib

6 of 6 total messages in 1 files
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5_p1.grib
era5_p1.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            10u          regular_ll   grid_simple  10           heightAboveGround 
1 of 1 messages in era5_p1.grib

1 of 1 total messages in 1 files
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5_p2.grib
era5_p2.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            10v          regular_ll   grid_simple  10           heightAboveGround 
1 of 1 messages in era5_p2.grib

1 of 1 total messages in 1 files
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5_p3.grib
era5_p3.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            2d           regular_ll   grid_simple  2            heightAboveGround 
1 of 1 messages in era5_p3.grib

1 of 1 total messages in 1 files
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5_p4.grib
era5_p4.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            2t           regular_ll   grid_simple  2            heightAboveGround 
1 of 1 messages in era5_p4.grib

1 of 1 total messages in 1 files
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5_p5.grib
era5_p5.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            z            regular_ll   grid_simple  0            surface     
1 of 1 messages in era5_p5.grib

1 of 1 total messages in 1 files
user@user-Computer:~/grib-test$ grib_ls -p "edition,shortName,gridType,packingType,level,typeOfLevel" era5_p6.grib
era5_p6.grib
edition      shortName    gridType     packingType  level        typeOfLevel  
2            sp           regular_ll   grid_simple  0            surface     
1 of 1 messages in era5_p6.grib

1 of 1 total messages in 1 files
``` 

Running this code (modified `list_surfaces.rs` example) in that folder produces below output:

Code:

```rust
use grib::codetables::{CodeTable4_2, Lookup};
use grib::context::Grib2;
use grib::reader::SeekableGrib2Reader;
use std::error::Error;
use std::fs::File;
use std::io::BufReader;
use std::path::Path;

fn main() -> Result<(), Box<dyn Error>> {
        println!("One file:");
        let path = Path::new("era5.grib");
        list_surfaces(path)?;

        println!("\nSplit files:");
        list_surfaces(Path::new("era5_p1.grib"))?;
        list_surfaces(Path::new("era5_p2.grib"))?;
        list_surfaces(Path::new("era5_p3.grib"))?;
        list_surfaces(Path::new("era5_p4.grib"))?;
        list_surfaces(Path::new("era5_p5.grib"))?;
        list_surfaces(Path::new("era5_p6.grib"))?;

        Ok(())
}

fn list_surfaces(path: &Path) -> Result<(), Box<dyn Error>> {
    // Open the input file in a normal way.
    let f = File::open(&path)?;
    let f = BufReader::new(f);
    let grib2 = Grib2::<SeekableGrib2Reader<BufReader<File>>>::read_with_seekable(f)?;

    for submessage in grib2.iter() {

        let discipline = submessage.indicator().discipline;
        let category = submessage.prod_def().parameter_category().unwrap();
        let parameter = submessage.prod_def().parameter_number().unwrap();
        let parameter = CodeTable4_2::new(discipline, category).lookup(usize::from(parameter));
        let forecast_time = submessage.prod_def().forecast_time().unwrap();
        let (first, _second) = submessage.prod_def().fixed_surfaces().unwrap();
        let elevation_level = first.value();

        println!(
            "{:<31} {:>14} {:>17}",
            parameter.to_string(),
            forecast_time.to_string(),
            elevation_level
        );
    }

    Ok(())
}
```

Output:

```bash
One file:
u-component of wind                      0 [h]                10

Split files:
u-component of wind                      0 [h]                10
v-component of wind                      0 [h]                10
Dewpoint temperature                     0 [h]                 2
Temperature                              0 [h]                 2
Geopotential                             0 [h]               NaN
Pressure                                 0 [h]               NaN
```

Clearly, the iterator does not return all messages in the file.

### Expected Behavior

The `SubMessageIterator` should iterate over all messages present in the `.grib` file instead of returning only the first one.

### Actual Behavior

`SubMessageIterator` `.next()` method  returns only first message from the file and then returns `None`.

**Comment by Quba1** [comment]
After some more research I found out that this is probably not a bug, but missing feature. Currently, the crate is reading a single GRIB message as defined in the WMO Manual on Codes. And thus `Grib2Read::scan()` stops reading the file as soon as it encounters `7777`.
But it seems to be a standard practice in some centers (eg. NCEP, ECMWF) to create GRIB files by appending GRIB messages to each other. This can be seen in the sizes of files in my example (parts add up exactly to the `era5.grib` file size) and in the `era5.grib` file itself. When decoded with `xxd -b` there are 5 occurrences of `7777GRIB` sequence in the file, indicating that beginning of the message is joined to the end of the previous message. Same thing appears in the GFS files as well.

As it is a rather common practice in the industry to create GRIB files like that, I think it is worth handling such cases in the crate, and add the feature for that.

My proposed solution is:
- Rename `Grib2` struct to `Grib2Message` to be specific what the type represents
- Add a new struct `Grib2Multi` (or similar), which will scan the file for GRIB Sections 0 (containing `GRIB` sequence and message size) and will hold an index of GRIB messages in the file (similar to `SubMessageIndex`)
- Implement `Iterator` trait for the new `Grib2Multi` type with the `next()` method that returns renamed `Grib2Message` struct

**Comment by noritada** [comment]
Thank you very much for your kind report.

I have not checked with the dataset you reported, but I can imagine that since I have known that issue. The cause seems to be as described in your comment.

For example, in wgrib2, if the input file contains a single message with 3 submessages, we can see display like this:

```shellsession
% wgrib2 input.grib
1.1:...
1.2:...
1.3:...
```

On the other hand, if the input file contains 3 messages with one sub-message, the display becomes like this:

```shellsession
% wgrib2 input.grib
1:...
2:...
3:...
```

I developed the initial version so that it could handle the former, but since I understood later that the latter is often present in actual published data, I considered I had to support the latter as well. I will try to support the latter earlier.
(The fact that the latter often exists can be seen from the fact that it is the latter that is generated when using the `-grib` option of `wgrib2`.)

**Comment by noritada** [comment]
I am working on this issue.

Previously, this library could only read, hold, and reference submessages in a specific message. To achieve the processing of multiple messages, we need to make changes to the read, hold, and reference parts respectively, which will require some efforts. At the moment, part of the reading part is being implemented in the master branch.

**Comment by brentlemons** [comment]
Do you have a branch where you are working on this? Any need for help?

**Comment by noritada** [comment]
@brentlemons Sorry. I must have missed your message. Thank you very much.

With the version I released today, I believe we are now able to properly handle data consisting of multiple messages. However, it is still not fully functional, so help is welcome.

(The implementation of the mechanism to process multi-message data was finished a few months ago, but I had other major API improvements that took a long time to release.)
