### ISSUE TITLE
cargo build fails because a file for gen/src/cct11.rs is missing

### ISSUE THREAD

**Issue by naschidaniel** [noritada/grib-rs#2]
## Description 
Thanks for the motivation to replace wgrib2. 
I tried to install the repo with cargo. But unfortunately a build error occurs. It seems that some data is missing.

## System Configuration:

* Fedora 33 - 5.11.7-200.fc33.x86_64
* rustc 1.50.0 (cb75ad5db 2021-02-10)
* cargo 1.50.0 (f04e7fab7 2021-02-04)

## Steps to reproduce
```
cargo build
``´
The error also occurs with `cargo test`  and `cargo run` .

## Error message
```
(base) [daniel@localhost:~/dev/grib-rs]$ cargo build
   Compiling grib-build v0.1.0 (/home/daniel/dev/grib-rs/gen)
   Compiling grib v0.2.0 (/home/daniel/dev/grib-rs)
error: failed to run custom build command for `grib v0.2.0 (/home/daniel/dev/grib-rs)`

Caused by:
  process didn't exit successfully: `/home/daniel/dev/grib-rs/target/debug/build/grib-1c47537ab65b4df2/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', gen/src/cct11.rs:10:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


## Additional information

The report is related to #1 .

Thank you very much,

Daniel

**Comment by Quba1** [comment]
Would you like to share the code you're trying to run?
I have ran my programs with this version of library, and didn't encounter any issues.

**Comment by naschidaniel** [comment]
I have only loaded the current master branch and entered the command `cargo build` in the main directory.
I thought that this would have allowed me to create the binary `gribber`.

**Comment by mulimoen** [comment]
@naschidaniel Seems like you have not pulled the submodules to get the XML definitions, try
```sh
git submodule update --init --recursive
```

**Comment by noritada** [comment]
Thank you very much for reporting. At the moment, this software is still not as full-featured as wgrib2, but we are working hard to make it more so.

As @mulimoen describes, this Git repository uses submodules. So, adding `--recursive` to the `git clone` command in cloning, or updating submodules afterwards by `git submodule update --init --recursive` would be required. I should add descriptions to README.md.

**Comment by naschidaniel** [comment]
Thank you very much for the help  @mulimoen and @noritada,
By downloading the submodules I was able to create the binary successfully.
Best regards
