### ISSUE TITLE
Lat/lon computation of grid points for CMC GDPS data fails

### ISSUE THREAD

**Issue by noritada** [noritada/grib-rs#51]
### Simple Description on the Bug

Lat/lon computation of grid points fails for `testdata/CMC_glb_TMP_ISBL_1_latlon.24x.24_2021051800_P000.grib2`.

It is because longitude range [180000000, 179760000] has a final value smaller than the initial value, although it is expected to increase from the scanning mode `0b01000000`.

### Steps to Reproduce

Test code using a grid definition extracted from that data is like this:

```rust
    #[test]
    fn cmc_gdps_lat_lon_grid() {
        let grid = LatLonGridDefinition::new(
            1500,
            751,
            -90000000,
            180000000,
            90000000,
            179760000,
            ScanningMode(0b01000000),
        );
        assert!(grid.latlons().is_ok())
    }
```

### Expected Behavior

Test passes.

### Actual Behavior

Test fails.

**Comment by raffaele-sg** [comment]
I have also encountered this issue with the ECMWF forecasts. Metview resolves the first longitude to `-180.000` whereas grib-rs finds `first_point_lon` to be `180.000.` 

When creating a `LatLonGridDefinition` manually with this sign adjustment, the `latlon` iterator seems to work fine.

I hope this is helpful

**Comment by noritada** [comment]
@raffaele-sg Thank you for the comment and sorry for putting off fixing this relatively simple problem.

Since GRIB2 allows data creators to define both longitude-increasing and longitude-decreasing grid point sets, I had given some thought to how it might be handled correctly, but I left it alone and proceeded to implement other major issues.

The fixes have been made and I hope to release a corrected version tomorrow.

**Comment by noritada** [comment]
@noritada TODO: Port the fix to Gaussian grids.

**Comment by raffaele-sg** [comment]
> @raffaele-sg Thank you for the comment and sorry for putting off fixing this relatively simple problem.
> 
> Since GRIB2 allows data creators to define both longitude-increasing and longitude-decreasing grid point sets, I had given some thought to how it might be handled correctly, but I left it alone and proceeded to implement other major issues.
> 
> The fixes have been made and I hope to release a corrected version tomorrow.

Thank you so much for the reply and the fix! 🎉
